### ISSUE TITLE
User exception (panic/abort/assert)

### ISSUE THREAD

**Issue by mozzhead164** [turgu1/mqtt_ota_example#1]
Hi, I am trying to implement this using an Wemos D1 Mini Pro (16MB)

Using Node-Red to send the firmware payload through node-red-contrib-aedes MQTT broker

The first message gets through;
```
Receive size: 262320
begin()
```

But sending the second message, the actual firmware, causes a crash. 
It causes a core panic with the exception: Panic core_esp8266_main.cpp:121 __yield

Should I be splitting the firmware payload up into smaller chunks or send as one big payload? 

I've tried;
- changing pubsubclient.h MQTT_MAX_PACKET_SIZE to 2048 and higher.
-  using a Split node to split the payload into 512 byte chunks.

But I still get the exception in the above cases

- commenting all callback code out and inserting just a; 
```
debug("msg received") 
```
there is no longer an exception. So its something to do with how the message is received or the length of the message. I dont think its getting as far as saving the buffer to memory - or even implementing the OTA itself.

Please can you help or give a bit of guidance into this issue for me. Even telling me how this should be effectively debugged. 

Many thanks

**Comment by turgu1** [comment]
Hello, I've been using this code with mosquitto MQTT broker without any problem. I've not touched this code since the time I've put in on GitHub. I understand the the original owner added my patch to pubsubclient to it's own copy of the library.

For sure you need to get the data through the stream capability, as the usual buffer will only receive the first portion of the the huge message. I presume that you are using the code here to do your tests?

**Comment by mozzhead164** [comment]
Yes I'm using the code here to test this with.
Still cannot get a large payload to not cause a crash. I cant work out how to debug this further

Here's the stack trace if your interested
```
Receive size: 262320
begin()

User exception (panic/abort/assert)
Panic core_esp8266_main.cpp:121 __yield

>>>stack>>>

ctx: sys
sp: 3fffede0 end: 3fffffb0 offset: 0000
3fffede0:  00000000 4bc6a7f0 974bc6a8 00000001  
3fffedf0:  000000fe 00000000 00000000 00000000  
3fffee00:  00000000 00000000 00000000 3ffeee0c  
3fffee10:  00000000 000000aa 40100274 00000000  
3fffee20:  0013c02a 3fffee82 3ffee400 40204dae  
3fffee30:  16d63113 00000000 3ffefb34 40204e0f  
3fffee40:  0013c02a 3fffee82 3ffee400 402048e1  
3fffee50:  00000004 3fffee82 3ffee400 402029d0  
3fffee60:  000000aa 3ffee400 3fffee80 00000218  
3fffee70:  00000004 3ffee400 00000406 40202b33  
3fffee80:  00aa0218 00000000 00000001 3ffe84f8  
3fffee90:  3fffeec0 00000001 fffffffd 00000030  
3fffeea0:  000000b0 00000016 3ffee400 0013c027  
3fffeeb0:  4d269a8f 3ffeec00 3ffee400 40202f88  
3fffeec0:  16d61102 0013c00e 00000020 4020e7dc  
3fffeed0:  00000000 00000000 00000013 4020fe35  
3fffeee0:  4020fe90 0013c00e 3ffef0b4 60000600  
3fffeef0:  4d269a8f 3ffeddd0 3ffee3ec 40201054  
3fffef00:  4d2639b2 3ffeddd0 3ffedda8 40206232  
3fffef10:  402303ac 3ffee3ec 3ffeddd0 4020651a  
3fffef20:  60000600 3ffee3ec 3ffeddd0 402303b9  
3fffef30:  402303fe 3fffdab0 00000000 3fffdcb0  
3fffef40:  3ffeddf0 3fffdad0 3ffeedcc 4020481f  
3fffef50:  40000f49 40000f49 3fffdab0 40000f49  
3fffef60:  40000e19 40001878 00000002 3fffffb0  
3fffef70:  3fffff10 aa55aa55 000000b0 40104999  
3fffef80:  4010499f 00000002 3fffffb0 00000049  
3fffef90:  4010000d 00000000 00000000 00000000  
3fffefa0:  00000000 3fffef3c 00000000 3ffffec8  
3fffefb0:  3fffffc0 00000000 00000000 feefeffe  
3fffefc0:  feefeffe feefeffe feefeffe feefeffe  
3fffefd0:  feefeffe feefeffe feefeffe feefeffe  
3fffefe0:  feefeffe feefeffe feefeffe feefeffe  
3fffeff0:  feefeffe feefeffe feefeffe feefeffe  
3ffff000:  feefeffe feefeffe feefeffe feefeffe  
3ffff010:  feefeffe feefeffe feefeffe feefeffe  
3ffff020:  feefeffe feefeffe feefeffe feefeffe  
3ffff030:  feefeffe feefeffe feefeffe feefeffe  
3ffff040:  feefeffe feefeffe feefeffe feefeffe  
3ffff050:  feefeffe feefeffe feefeffe feefeffe  
3ffff060:  feefeffe feefeffe feefeffe feefeffe  
3ffff070:  feefeffe feefeffe feefeffe feefeffe  
3ffff080:  feefeffe feefeffe feefeffe feefeffe  
3ffff090:  feefeffe feefeffe feefeffe feefeffe  
3ffff0a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff0b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff0c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff0d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff0e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff0f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff100:  feefeffe feefeffe feefeffe feefeffe  
3ffff110:  feefeffe feefeffe feefeffe feefeffe  
3ffff120:  feefeffe feefeffe feefeffe feefeffe  
3ffff130:  feefeffe feefeffe feefeffe feefeffe  
3ffff140:  feefeffe feefeffe feefeffe feefeffe  
3ffff150:  feefeffe feefeffe feefeffe feefeffe  
3ffff160:  feefeffe feefeffe feefeffe feefeffe  
3ffff170:  feefeffe feefeffe feefeffe feefeffe  
3ffff180:  feefeffe feefeffe feefeffe feefeffe  
3ffff190:  feefeffe feefeffe feefeffe feefeffe  
3ffff1a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff1b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff1c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff1d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff1e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff1f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff200:  feefeffe feefeffe feefeffe feefeffe  
3ffff210:  feefeffe feefeffe feefeffe feefeffe  
3ffff220:  feefeffe feefeffe feefeffe feefeffe  
3ffff230:  feefeffe feefeffe feefeffe feefeffe  
3ffff240:  feefeffe feefeffe feefeffe feefeffe  
3ffff250:  feefeffe feefeffe feefeffe feefeffe  
3ffff260:  feefeffe feefeffe feefeffe feefeffe  
3ffff270:  feefeffe feefeffe feefeffe feefeffe  
3ffff280:  feefeffe feefeffe feefeffe feefeffe  
3ffff290:  feefeffe feefeffe feefeffe feefeffe  
3ffff2a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff2b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff2c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff2d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff2e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff2f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff300:  feefeffe feefeffe feefeffe feefeffe  
3ffff310:  feefeffe feefeffe feefeffe feefeffe  
3ffff320:  feefeffe feefeffe feefeffe feefeffe  
3ffff330:  feefeffe feefeffe feefeffe feefeffe  
3ffff340:  feefeffe feefeffe feefeffe feefeffe  
3ffff350:  feefeffe feefeffe feefeffe feefeffe  
3ffff360:  feefeffe feefeffe feefeffe feefeffe  
3ffff370:  feefeffe feefeffe feefeffe feefeffe  
3ffff380:  feefeffe feefeffe feefeffe feefeffe  
3ffff390:  feefeffe feefeffe feefeffe feefeffe  
3ffff3a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff3b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff3c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff3d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff3e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff3f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff400:  feefeffe feefeffe feefeffe feefeffe  
3ffff410:  feefeffe feefeffe feefeffe feefeffe  
3ffff420:  feefeffe feefeffe feefeffe feefeffe  
3ffff430:  feefeffe feefeffe feefeffe feefeffe  
3ffff440:  feefeffe feefeffe feefeffe feefeffe  
3ffff450:  feefeffe feefeffe feefeffe feefeffe  
3ffff460:  feefeffe feefeffe feefeffe feefeffe  
3ffff470:  feefeffe feefeffe feefeffe feefeffe  
3ffff480:  feefeffe feefeffe feefeffe feefeffe  
3ffff490:  feefeffe feefeffe feefeffe feefeffe  
3ffff4a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff4b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff4c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff4d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff4e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff4f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff500:  feefeffe feefeffe feefeffe feefeffe  
3ffff510:  feefeffe feefeffe feefeffe feefeffe  
3ffff520:  feefeffe feefeffe feefeffe feefeffe  
3ffff530:  feefeffe feefeffe feefeffe feefeffe  
3ffff540:  feefeffe feefeffe feefeffe feefeffe  
3ffff550:  feefeffe feefeffe feefeffe feefeffe  
3ffff560:  feefeffe feefeffe feefeffe feefeffe  
3ffff570:  feefeffe feefeffe feefeffe feefeffe  
3ffff580:  feefeffe feefeffe feefeffe feefeffe  
3ffff590:  feefeffe feefeffe feefeffe feefeffe  
3ffff5a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff5b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff5c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff5d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff5e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff5f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff600:  feefeffe feefeffe feefeffe feefeffe  
3ffff610:  feefeffe feefeffe feefeffe feefeffe  
3ffff620:  feefeffe feefeffe feefeffe feefeffe  
3ffff630:  feefeffe feefeffe feefeffe feefeffe  
3ffff640:  feefeffe feefeffe feefeffe feefeffe  
3ffff650:  feefeffe feefeffe feefeffe feefeffe  
3ffff660:  feefeffe feefeffe feefeffe feefeffe  
3ffff670:  feefeffe feefeffe feefeffe feefeffe  
3ffff680:  feefeffe feefeffe feefeffe feefeffe  
3ffff690:  feefeffe feefeffe feefeffe feefeffe  
3ffff6a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff6b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff6c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff6d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff6e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff6f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff700:  feefeffe feefeffe feefeffe feefeffe  
3ffff710:  feefeffe feefeffe feefeffe feefeffe  
3ffff720:  feefeffe feefeffe feefeffe feefeffe  
3ffff730:  feefeffe feefeffe feefeffe feefeffe  
3ffff740:  feefeffe feefeffe feefeffe feefeffe  
3ffff750:  feefeffe feefeffe feefeffe feefeffe  
3ffff760:  feefeffe feefeffe feefeffe feefeffe  
3ffff770:  feefeffe feefeffe feefeffe feefeffe  
3ffff780:  feefeffe feefeffe feefeffe feefeffe  
3ffff790:  feefeffe feefeffe feefeffe feefeffe  
3ffff7a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff7b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff7c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff7d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff7e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff7f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff800:  feefeffe feefeffe feefeffe feefeffe  
3ffff810:  feefeffe feefeffe feefeffe feefeffe  
3ffff820:  feefeffe feefeffe feefeffe feefeffe  
3ffff830:  feefeffe feefeffe feefeffe feefeffe  
3ffff840:  feefeffe feefeffe feefeffe feefeffe  
3ffff850:  feefeffe feefeffe feefeffe feefeffe  
3ffff860:  feefeffe feefeffe feefeffe feefeffe  
3ffff870:  feefeffe feefeffe feefeffe feefeffe  
3ffff880:  feefeffe feefeffe feefeffe feefeffe  
3ffff890:  feefeffe feefeffe feefeffe feefeffe  
3ffff8a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff8b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff8c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff8d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff8e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff8f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff900:  feefeffe feefeffe feefeffe feefeffe  
3ffff910:  feefeffe feefeffe feefeffe feefeffe  
3ffff920:  feefeffe feefeffe feefeffe feefeffe  
3ffff930:  feefeffe feefeffe feefeffe feefeffe  
3ffff940:  feefeffe feefeffe feefeffe feefeffe  
3ffff950:  feefeffe feefeffe feefeffe feefeffe  
3ffff960:  feefeffe feefeffe feefeffe feefeffe  
3ffff970:  feefeffe feefeffe feefeffe feefeffe  
3ffff980:  feefeffe feefeffe feefeffe feefeffe  
3ffff990:  feefeffe feefeffe feefeffe feefeffe  
3ffff9a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff9b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff9c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff9d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff9e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff9f0:  feefeffe feefeffe feefeffe feefeffe  
3ffffa00:  feefeffe feefeffe feefeffe feefeffe  
3ffffa10:  feefeffe feefeffe feefeffe feefeffe  
3ffffa20:  feefeffe feefeffe feefeffe feefeffe  
3ffffa30:  feefeffe feefeffe feefeffe feefeffe  
3ffffa40:  feefeffe feefeffe feefeffe feefeffe  
3ffffa50:  feefeffe feefeffe feefeffe feefeffe  
3ffffa60:  feefeffe feefeffe feefeffe feefeffe  
3ffffa70:  feefeffe feefeffe feefeffe feefeffe  
3ffffa80:  feefeffe feefeffe feefeffe feefeffe  
3ffffa90:  feefeffe feefeffe feefeffe feefeffe  
3ffffaa0:  feefeffe feefeffe feefeffe feefeffe  
3ffffab0:  feefeffe feefeffe feefeffe feefeffe  
3ffffac0:  feefeffe feefeffe feefeffe feefeffe  
3ffffad0:  feefeffe feefeffe feefeffe feefeffe  
3ffffae0:  feefeffe feefeffe feefeffe feefeffe  
3ffffaf0:  feefeffe feefeffe feefeffe feefeffe  
3ffffb00:  feefeffe feefeffe feefeffe feefeffe  
3ffffb10:  feefeffe feefeffe feefeffe feefeffe  
3ffffb20:  feefeffe feefeffe feefeffe feefeffe  
3ffffb30:  feefeffe feefeffe feefeffe feefeffe  
3ffffb40:  feefeffe feefeffe feefeffe feefeffe  
3ffffb50:  feefeffe feefeffe feefeffe feefeffe  
3ffffb60:  feefeffe feefeffe feefeffe feefeffe  
3ffffb70:  feefeffe feefeffe feefeffe feefeffe  
3ffffb80:  feefeffe feefeffe feefeffe feefeffe  
3ffffb90:  feefeffe feefeffe feefeffe feefeffe  
3ffffba0:  feefeffe feefeffe feefeffe feefeffe  
3ffffbb0:  feefeffe feefeffe feefeffe feefeffe  
3ffffbc0:  feefeffe feefeffe feefeffe feefeffe  
3ffffbd0:  feefeffe feefeffe feefeffe feefeffe  
3ffffbe0:  feefeffe feefeffe feefeffe feefeffe  
3ffffbf0:  feefeffe feefeffe feefeffe feefeffe  
3ffffc00:  00000000 00000000 0000001f 4010017c  
3ffffc10:  feefeffe feefeffe 3fffc228 40105139  
3ffffc20:  4000050c feefeffe 4022a3c7 00000001  
3ffffc30:  ffffffff 00000000 3ffe8c11 00000008  
3ffffc40:  4022a416 3ffec230 3ffef4d4 00000001  
3ffffc50:  00000002 00000000 4022a3c7 00000001  
3ffffc60:  ffffffff 00000000 3ffe8c11 00000008  
3ffffc70:  00000000 00000000 0000001f 4010017c  
3ffffc80:  ffffffff 00000000 3fffc228 40105139  
3ffffc90:  4000050c 3ffec258 3ffef4d4 00000001  
3ffffca0:  4010353e 00000030 00000000 fffffffe  
3ffffcb0:  3ff20a00 01000000 00000000 00000000  
3ffffcc0:  00000000 0002c858 00000000 3ffecab0  
3ffffcd0:  00000000 00000000 0000001f 4010017c  
3ffffce0:  00200000 00040000 3fffc228 40105139  
3ffffcf0:  00000000 00000000 0000001f 4010017c  
3ffffd00:  40102174 00000030 3fffc228 40105139  
3ffffd10:  4000050c 00000001 3ffe934c 3ffe99d4  
3ffffd20:  401048a6 00000030 0000001f fffffffe  
3ffffd30:  40102239 3ffecf98 00000001 4acff3b9  
3ffffd40:  00000001 00000000 00000001 3ffeedcc  
3ffffd50:  00000000 3ffe9340 00000001 3ffe937c  
3ffffd60:  3ffeb2e4 00000000 00002200 00000030  
3ffffd70:  4010272a 00000030 00000019 fffffffe  
3ffffd80:  4000050c 00000000 00000001 000000cf  
3ffffd90:  0000005c 00000001 401047e1 3ffecc88  
3ffffda0:  3ffecc10 00000000 00000020 4010017c  
3ffffdb0:  0000005e 00000000 00000005 000000f8  
3ffffdc0:  401043c6 3ffecc88 401047e1 3ffecc88  
3ffffdd0:  3ffecc10 40103c31 3ffecc88 3ffecc88  
3ffffde0:  3ffecc10 4d257b7a 3ffecf98 4010235c  
3ffffdf0:  401042c9 3ffecc88 3ffec258 00040000  
3ffffe00:  23002200 40103c31 3ffecc88 00000100  
3ffffe10:  40104542 00080000 00000002 00000001  
3ffffe20:  40102887 3ffecc88 3ffec258 00040000  
3ffffe30:  23002200 00000000 0000007f 00040000  
3ffffe40:  40104542 2c9f0300 4000050c 3fffc278  
3ffffe50:  40102540 3fffc200 00000022 00040000  
3ffffe60:  40205e2a 00000030 00000010 ffffffff  
3ffffe70:  00000000 00000000 0000001f 4010017c  
3ffffe80:  00000000 00000000 3fffc228 40105139  
3ffffe90:  4000050c 3fffc6fc 00000001 3ffeed8c  
3ffffea0:  40204862 00000030 00000010 ffffffff  
3ffffeb0:  402049a4 000000a0 00000001 00000001  
3ffffec0:  00000000 00000000 00000000 fffffffe  
3ffffed0:  ffffffff 3fffc6fc 00000001 3ffe84f8  
3ffffee0:  00000000 3fffdad0 3ffeedcc 00000030  
3ffffef0:  ffffffff 3fffc6fc 00000001 3ffe84f8  
3fffff00:  00000000 3fffdad0 3ffeedcc 00000030  
3fffff10:  00000001 002204a5 40203162 3ffee3d8  
3fffff20:  00000001 00000032 3ffee3d8 40202eda  
3fffff30:  402034fc 3ffeeca0 3ffe86dd 00000001  
3fffff40:  00000000 00000000 3ffeeca0 00000001  
3fffff50:  00000000 00000000 3ffeeca0 402012e9  
3fffff60:  00f42400 a536352e 00000000 feefeffe  
3fffff70:  00000000 00000000 00000000 00000000  
3fffff80:  00000000 00000000 00000001 4010017c  
3fffff90:  3fffdad0 00000000 3ffeed8c 4010019d  
3fffffa0:  3fffdad0 00000000 3ffeed8c 402049c1  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1392, room 16 
tail 0
chksum 0xd0
csum 0xd0
v3d128e5c
~ld
Free Sketch Space: 1806336
Sketch size: 288192
Chip size: 16777216

```

**Comment by turgu1** [comment]
I've integrated that code into my home system IOT framework. You will find it in my GitHub repository named "maison". I'm using it with version the framework espressif8266@2.2.3 .  If you look inside the file named src/maison.cpp you will see a portion of the code that is almost identical with the example code, with added md5 check and other goodies. Maybe it's related to the framework version you are using. Can you try with version 2.2.3?

**Comment by turgu1** [comment]
Are-you using PlatformIO?

**Comment by turgu1** [comment]
With my own environment, I'm able to transmit binaries as long as 450K without any issues, using Mosquitto server in its standard configuration with added encryption and username/password. The data is sent as one big message, preceded with a a message that gives data size and other added information. In the maison repository, you can look at file tools/upload.sh that I'm using to upload new program versions through MQTT OTA.

**Comment by mozzhead164** [comment]
Not using platformIO...im using Arduino IDE, tried PIO a few months ago but there were troubles with my install and i couldnt get rid of the errors it was throwing.

Just upgraded to core 2.7.0 via Arduino IDE but still getting errors.
Will give the above advice a try and let you know how i get on.
Could it be that nodered is pushing the data out to Aedes broker in a wrong format?

If i do split the message, does the ESP code know how to arrange this back into a single message in the right order? Should i therefore be using QOS 1 with a count variable so the order is known at the destination? 

Many thanks for your help BTW

**Comment by turgu1** [comment]
If you use QOS 1, depending on the MQTT server, it may stay in the queue and sent back every time the device re-connect. Depends the way the server is implementing QOS 1. I've seen that before.

Normally, messages are supposed to be sent using the same sequence as they appeared at the entry of the server. One thing you can do is try to retrieve the data elsewhere in your computer and compare the data sent with the data transmitted, to see if there is any difference.

I've never used something else than PatformIO with this code.

**Comment by turgu1** [comment]
Another point, be sure to use the patched version of pubsubclient. It allows for messages larger than 64k. The one available in my github repository is.

**Comment by mozzhead164** [comment]
Thanks for your help yesterday.
Am i using the master branch or the branches labelled patch-1 or patch-2?

Narrowed it down slightly with an mqtt-benchmark test. 

The test passed with a message of ~500KB data throughput so i know it is definitely not the Aedes broker limiting the message size. 

It has to be either pubsubclient not allowing this size of message, or I am sending the firmware in the wrong data type from nodered. 

In order to rule out the latter please could you look over these settings...

I am using a simple 'File-in' node with simple blink sketch as the filename (/data/blink-ota.bin)
[[I'm using Docker, so i have to mention that ive bind-mounted a local directory to /data inside the nodered container]]

The file-in node can give several different types of output, i have tried many.
The default is a single buffer object
I have also tried single utf8 string (To which i get more options when selected)
There are many sub-options for utf8 string decoding, such as Hex, Binary, utf8, ascii, base64
I think i have tried almost all of these (there are loads more) to which i always get the crash...

I am running out of options for troubleshooting. But i have a few hours tonight to dig a little deeper

**Comment by turgu1** [comment]
For pubsubclient, you have to use the master branch.

The data is sent as a big binary chunk. I would try, if you can, use a *simple* char buffer, as I don’t expect you need any interpretation done.

In your test, beyond looking at the size, have you verified that the content is exactly the same from the one that was sent?

Good luck!
Guy

**Comment by mozzhead164** [comment]
What do you have your MQTT_MAX_PACKET_SIZE set to?

**Comment by turgu1** [comment]
1024

**Comment by mozzhead164** [comment]
If I change it to 1024 any messages above this do not get read into the callback function though.

I'm using a dummy buffer in nodered (injecting a buffer of 1,2,3....1024 works but 1-1025 doesn't)

Sorry about all this hassle i'm sure you have better things to be doing...

**Comment by turgu1** [comment]
The point is you won't get more than the first 1024 bytes in a callback. This is not the way to retrieve a large amount of data. You have to use the stream capability, as shown in the example code.

**Comment by mozzhead164** [comment]
oh fair enough...I was trying to grab the data received so i could compare it to what was output from nodered...

**Comment by mozzhead164** [comment]
I somehow managed to get it working.
Started afresh - erased ESP flash and re-downloaded your sketch 
Now its started to work - sucessfully uploaded the blink sketch

Apologies for taking up so much of your time, and thanks for the effort youve put in.
Could i donate you a beer or two..?

**Comment by turgu1** [comment]
It was a pleasure for me to try to help you. Hope the best for your project. I will leave this open for a week in case you need more help.

Cheers!

Guy

**Comment by mozzhead164** [comment]
Thanks Guy, much appreciated !

In case your interested - a few details about the project

Its a cluster of Raspberry pi 4b's [4GB] - (8 of these in total)
Running Docker Swarm with Nodered, Aedes MQTT Broker, AWS DynamoDB, Traefik etc etc
Each Pi has its own 240GB SSD which are together in a clustered file system - GlusterFS

This is all to learn the principals of clustering computers, a bit of a homelab and research for a work project. Eventually will have many remote ESP8266's in the field for monitoring purposes. As the number of ESP's grows, so can the cluster. Docker is great for this as it allows you to scale horizontally adding more and more 'containers' which are just isolated applications. So i can run 64 instances of Nodered and Aedes broker to handle extra throughput (Switched from Mosquitto Broker as it doesnt handle clustering really well). Each application will have its respective ports needed for communication, so i have used Traefik to handle all the endpoints that point to my external IP and route traffic automatically to the correct application port. All while handling automatic SSL certs renewal etc etc.

As the devices are remote, I will never have an opportunity to update the code on any of the devices. I have created a Nodered flow to handle OTA updates through the normal ArduinoOTA library, but doing this securely required two sets of SSL certification and therefore taking up a lot more memory on the ESP. This method allows me to just use one set of certs for secure MQTT connection and reduce the codes memory footprint. Updates and user data going through the same channel of communication. So many thanks for the work done here and I appreciate the help you have given me. Thanks man, really appreciate it

**Comment by turgu1** [comment]
It seems to be an interesting project. I will certainly look at the Aedes broker in the future.

Take care!
Guy

**Comment by mozzhead164** [comment]
Sorry just one more quick question.
Is this code compatible with SPIFFS uploads or is it just sketch only?

**Comment by turgu1** [comment]
Sketch only. I don’t know if there is another entry point in the framework to update spiffs. In my own design, to update a file in spiffs, I simply open a temporary file inside spiffs. Once the file has been received, I delete the old file and rename de new one.

**Comment by mozzhead164** [comment]
I'm not sure i understand that fully but i'll surely give it a shot.
Basically, send the file needed for spiffs inside the program code, and in the program save to spiffs and delete the data? hmmm ok doesnt seem too hard

**Comment by turgu1** [comment]
Just as you would do on a regular computer.
